### ISSUE TITLE
Strange issue on pod update

### ISSUE THREAD

**Issue by jessejamesrichard** [kseebaldt/deferred#48]
```
The platform of the target `Pods` (tvOS 9.0) is not compatible with `KSDeferred (0.3.0)`, which does not support `tvos`.
```

But it seems to be included in the podspec.

**Comment by briancroom** [comment]
Hey @jessejamesrichard, it looks like there hasn't been a new release cut or pushed to trunk since tvOS support was added to the podspec. If @kseebaldt has some time, maybe he could cut a release for you?

In the meantime you should be able to point to the master branch in your Podfile instead of letting CocoaPods select a release:

```
pod 'KSDeferred', :git => 'https://github.com/kseebaldt/deferred.git'
```

**Comment by jessejamesrichard** [comment]
Thanks very much. Note the same thing on Cedar. Thoughts on the proper git for that since the podfile is the same?

**Comment by briancroom** [comment]
Oh, right. IIRC CocoaPods' tvOS support was still in beta when the last Cedar release occurred so the processed podspec didn't include that platform. The same technique should work there:
```
pod 'Cedar', :git => 'https://github.com/pivotal/cedar.git'
```

**Comment by jessejamesrichard** [comment]
Gotcha. 

Thanks!
